import { asyncActionType } from '../../utils'

export const SEARCH_GITHUB_REPOSITORIES = asyncActionType('SEARCH_GITHUB_REPOSITORIES')
export const CLEAR_GITHUB_REPOSITORIES = 'CLEAR_GITHUB_REPOSITORIES'
export const FETCH_GITHUB_PROFILE = asyncActionType('FETCH_GITHUB_PROFILE')
export const RELOAD_GITHUB_PROFILE = 'RELOAD_GITHUB_PROFILE'
